name: thirdle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  hmssdk_flutter: ^0.7.6
  http: ^0.13.5
  oktoast: ^3.3.1
  permission_handler: ^10.0.1
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/answer_words.txt
    - assets/valid_words.txt
    # credit: https://pngimg.com/image/83332
    - assets/game_over.png
    # credit: https://pngtree.com/freepng/game-text-you-win-retro-glitch-effect_6006883.html
    - assets/you_win.png